otawind/urls.py
from django.contrib import admin
from django.urls import include, path
from company import views
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.conf.urls import handler404

urlpatterns = [
    path('generar_url/', views.generar_url, name="generar_url"),
    path('url_catalogo/', views.generar_url, name="url_catalogo"),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', views.home, name="home"),
    path('home/<str:name>', views.index, name="index"),
    path("registro", views.signUp, name="registro"),
    path("accounts/login/", views.logIn, name="ingreso"),
    path('logout/', views.logOut, name="logout"),
    path('creacion/', views.createAccount, name="creacion"),
    path('dashboard/<str:name>/',login_required(views.dashboard), name="dashboard"),
    path('bussines-profile/',login_required(views.bussines), name="bussines"),
    path('perfil/<str:name>/<int:id>',login_required(views.profile), name="perfil"),
    path('edicion-perfil/<int:id>',login_required(views.editionProfile), name="edicionPerfil"),
    path('seleccionar-perfil',login_required(views.selectCatalog), name="selectPerfil"),
    path('agregar-catalogo/<int:id>',login_required(views.addCatalog), name="addCatalogo"),
    path('ver-catalogo/<str:name>/<int:id>', login_required(views.viewCatalogUser), name="viewCatalogo"),
    path('edicion-catalogo/<int:id>', login_required(views.editCatalog), name="edicionCatalogo"),
    path('eliminar-catalogo/<int:id>', login_required(views.deleteCatalog), name="eliminarCatalogo"),
    path('productos/<str:name>/<int:id>', login_required(views.viewProduct), name="productos"),
    path('agregar-producto/<str:name>/<int:id>', login_required(views.addProduct), name="addProductos"),
    path('editar-producto/<str:name>/<int:id>', login_required(views.editProduct), name="edicionProducto"),
    path('eliminar-producto/<int:id>', login_required(views.deleteProduct), name="eliminarProducto"),
    path('servicios/<str:name>/<int:id>', login_required(views.viewService), name="servicios"),
    path('agregar-servicio/<str:name>/<int:id>', login_required(views.addService), name="addServicios"),
    path('editar-servicio/<str:name>/<int:id>', login_required(views.editService), name="edicionServicio"),
    path('perfil-usuario/<str:name>/<int:id>', login_required(views.view_profile), name="viewPerfil"),
    path('catalogo/<str:name_profile>/<str:name>/<int:id>', views.viewCatalog, name="verCatalogo"),
    path('acerca-de-otawind/', views.acercaDe, name="acercaDe"),
]



# cONFIGURACION PARA CARGAR IMAGENES
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

company/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Color(models.Model):
    name = models.CharField(max_length=30)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="fecha creacion")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="fecha actualizacion")

class Account(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    photo_profile = models.ImageField(upload_to="perfil_bussines", verbose_name="perfil", null=True)
    birthday = models.DateTimeField(auto_now=False, auto_now_add=False, verbose_name="Cumpleaños")
    country = models.CharField(max_length=50, verbose_name='Pais')
    city = models.CharField(max_length=50, verbose_name='Ciudad')
    bio = models.TextField(max_length=50, null=True)
    email = models.EmailField(max_length=254, verbose_name='Correo')
    facebook = models.CharField(max_length=300, null=True)
    instagram = models.CharField(max_length=300, null=True)
    whatsapp = models.CharField(max_length=300, null=True)
    indicative = models.CharField(max_length=3, verbose_name="Indicativo")
    contact = models.CharField(null=True, max_length=30, verbose_name="Contacto")
    gender = models.CharField(
        verbose_name = 'Genero',
        null=True,
        max_length=6,
        choices=[('Hombre','Hombre'),('Mujer','Mujer'),('Otros','Otros')]
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="fecha creacion")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="fecha actualizacion")

    def __str__(self):
        return self.user.username
    

class Category(models.Model):
    name = models.CharField(max_length=200, verbose_name = "Nombre")
    type_categorie = models.CharField(max_length=15, verbose_name= "tipo_categoria")
    description = models.TextField(verbose_name="descripcion")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="fecha creacion")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="fecha actualizacion")

    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"
    
    def __str__(self):
        return self.name
    
class ProfileBussines(models.Model):
    name = models.CharField(max_length=100, verbose_name="nombre")
    user = models.ForeignKey(User, verbose_name="usuario" , on_delete=models.CASCADE)
    bio = models.TextField(max_length=50, null=True)
    category = models.ForeignKey(Category, verbose_name="categoria", on_delete=models.CASCADE, default=True)
    photo_portada = models.ImageField(upload_to="perfil_bussines", verbose_name="portada", null=True)
    photo_profile = models.ImageField(upload_to="perfil_bussines", verbose_name="perfil", null=True)
    description = models.TextField(max_length=500, verbose_name="descripcion")
    contact = models.CharField(max_length=50, verbose_name="contacto")
    email = models.EmailField(max_length=254, verbose_name="correo")
    facebook = models.CharField(max_length=300, null=True)
    instagram = models.CharField(max_length=300, null=True)
    whatsapp = models.CharField(max_length=300, null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="fecha creacion")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="fecha actualizacion")
    class Meta:
        verbose_name = "Perfil-Empresa"
        verbose_name_plural = "Perfiles-Empresas"

    
    def __str__(self):
        return self.name

class Catalogos(models.Model):
    name = models.CharField(max_length=40, verbose_name="nombre")
    user = models.ForeignKey(User, verbose_name="user", on_delete=models.CASCADE, null=True)
    profile = models.ForeignKey(ProfileBussines, verbose_name="perfil", on_delete=models.CASCADE, null=True)
    category = models.ForeignKey(Category, verbose_name="categoria", on_delete=models.CASCADE)
    type_catalog = models.CharField(
        max_length = 10,
        verbose_name = 'Tipo catalogo',
        choices = [('Servicios','Servicios'),('Productos','Productos')]
    )
    description = models.TextField(max_length=1000, null=True, verbose_name="descripcion")
    photo_portada = models.ImageField(upload_to="catalogo", verbose_name="portada", null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="fecha creacion")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="fecha actualizacion")
    class Meta:
        verbose_name = "Catalogo"
        verbose_name_plural = "Catalogos"
    
    def __str__(self):
        return self.name
    
class Products(models.Model):
    name_product = models.CharField(max_length=100, verbose_name="Nombre")
    user = models.ForeignKey(User, verbose_name="user", on_delete=models.CASCADE)
    catalog = models.ForeignKey(Catalogos, verbose_name="catalogo", on_delete=models.CASCADE, related_name='product')
    id_product = models.CharField(max_length=10, unique=True, verbose_name="id_producto")
    profile = models.ForeignKey(ProfileBussines, verbose_name="Perfil", on_delete=models.CASCADE, null=True)
    category = models.ForeignKey(Category, verbose_name="Categoria", on_delete=models.CASCADE, default="None")
    quantities = models.CharField(max_length=4, verbose_name="Cantidades", null=True)
    brand = models.CharField(max_length=30, verbose_name="Marca")
    status = models.CharField(max_length=20, verbose_name="estado", default='Activo')
    color = models.CharField(max_length=50, null=True)
    valoration = models.CharField(verbose_name="Valoracion", max_length=3, default='3.5')
    price = models.IntegerField(verbose_name="precio")
    price_promo = models.IntegerField(verbose_name='promocion', default="0")
    description = models.TextField(max_length=1000, verbose_name="descripcion", default="Descripcion del producto")
    photo_product1 = models.ImageField(upload_to="productos", verbose_name="foto_producto1")
    photo_product2 = models.ImageField(upload_to="productos", verbose_name="foto_producto2", null=True)
    photo_product3 = models.ImageField(upload_to="productos", verbose_name="foto_producto3", null=True)
    photo_product4 = models.ImageField(upload_to="productos", verbose_name="foto_producto4", null=True)
    class Meta:
        verbose_name = "Producto"
        verbose_name_plural = "Productos"
    
    def __str__(self):
        return self.name_product
    

class Services(models.Model):
    name_service = models.CharField(max_length=40, verbose_name="Nombre")
    user = models.ForeignKey(User, verbose_name="user", on_delete=models.CASCADE)
    catalog = models.ForeignKey(Catalogos, verbose_name="catalogo", on_delete=models.CASCADE, related_name='service')
    id_service = models.CharField(max_length=10, unique=True, verbose_name="id_servicio")
    profile = models.ForeignKey(ProfileBussines, verbose_name="Perfil", on_delete=models.CASCADE, null=True)
    category = models.ForeignKey(Category, verbose_name="Categoria", on_delete=models.CASCADE, default="None")
    valoration = models.CharField(verbose_name="Valoracion", max_length=3, default='3.5')
    status = models.CharField(max_length=20, verbose_name="estado", default='Activo')
    price = models.IntegerField(verbose_name="precio")
    price_promo = models.IntegerField(verbose_name='promocion', default="0")
    description = models.TextField(max_length=1000, verbose_name="descripcion", default="Descripcion del servicio")
    photo_service1 = models.ImageField(upload_to="servicios", verbose_name="foto_servicio1")
    photo_service2 = models.ImageField(upload_to="servicios", verbose_name="foto_servicio2", null=True)
    photo_service3 = models.ImageField(upload_to="servicios", verbose_name="foto_servicio3", null=True)
    photo_service4 = models.ImageField(upload_to="servicios", verbose_name="foto_servicio4", null=True)
    class Meta:
        verbose_name = "Servicio"
        verbose_name_plural = "Servicios"
    
    def __str__(self):
        return self.name_service

company/templates/company_templates/crud-catalogo/add-catalogo.html
{% extends 'company_templates/layouts/layout.html' %}
{% load static %}
{% block title %}
    Agregar Catalogo
{% endblock title %}

{% block content %}
    <div class="content-catalogos">
        {% include 'company_templates/layouts/layout-dashboard.html' %} 
        <div class="content-catalogos-general">
            {% comment %} Mensaje flash {% endcomment %}
            {% for msg in messages %}
            {% if msg.tags == 'error' %}
            <div id="error">
                <div id="content-error"><p>{{msg}}</p></div>
            </div>
            {% else %}
            <div id="success">
                <div id="content-success"><p>{{msg}}</p></div>
            </div>
            {% endif %}
            {% endfor %}
            {% comment %} Fin mensaje flash {% endcomment %}
            <div class="content-form">
                <h1>Agrega tus catalogos</h1>
                {% include "company_templates/layouts/form.html" %}
            </div>
        </div>
    </div>
{% endblock content %}


{% block script %}
<script src="{% static '../static/js/jquery-3.6.4.js' %}"></script>
<script>

    $(document).ready(()=>{
        //Agregando texto a los recuadros de input type="file"
        $('#msg-file-photo_portada').html('<div style="cursor:pointer; text-align:center;"><i style="color:#7D05B4;" class="fa-regular fa-upload"><span style="font-size:14px;">Seleccionar</span></i><span style="font-size:14px"> o arrastrar el archivo hasta aqui.</span><p style="font-size:12px; text-align:center;">Sube tu imagen en JPG, PNG, JPEG, WEBP hasta de 5 MB de peso.</p></div>')

        // Solo imagenes
        $('input[type=file]').attr('accept','image/.jpg, .png, .jpeg, .webp');


        // Validacion de INPUT file
        $('#id_photo_portada').on("change", function(){
            if($('id_photo_portada').value != null){
                console.log('vacio')
            }else{
                const archivo = this.value.replace('C:\\fakepath\\','')
                //const nameArc = archivo.replace('fakepath',' ')
                $('#msg-file-photo_portada').html('<div> <p style="font-size:12px; text-align:center;">Se a cargado su imagen con exito.</p></div>')
                $('#arc-photo_portada').html(archivo)  
            }  
        })

    })

</script>    

{% endblock script %}

company/templates/company_templates/crud-catalogo/edit-catalog.html
{% extends 'company_templates/layouts/layout.html' %}
{% load mathfilters %}
{% load static %}
{% block title %}
    Editar Catalogo
{% endblock title %}

{% block content %}
    <div class="content-catalogos">
        {% include 'company_templates/layouts/layout-dashboard.html' %}
        <div class="content-catalogos-general">
            <h2 class="title-catalogo">Selecciona tu catalogo</h2>
            <div class="content-catalogo-general-box">
                {% for catalogo in catalogos %}
                <div class="card-catalogo">
                    <div id ="card-catalogo-face-{{catalogo.id}}" class="card-catalogo-face">
                        <div class="card-catalogo-face-portada">
                            <img src="{{catalogo.photo_portada.url}}">
                        </div>
                        <div class="card-catalogo-face-descripcion">
                            <input type="text" style="opacity:0;" id="id-{{forloop.counter}}" value="{{catalogo.id}}">
                            <h2 id="id-{{catalogo.id}}">{{catalogo.name}}</h2>
                            {% if catalogo.type_catalog == 'Productos' %}
                            {% for catalogs in cant_catalogs %}
                                {% if catalogs.id == catalogo.id and catalogo.type_catalog == 'Productos' %}
                                    <h3 id="cantProduct-{{forloop.counter}}">{{catalogs.cantPro}}</h3>
                                {% endif %}
                            {% endfor %}
                            {% endif %}

                            {% if catalogo.type_catalog == 'Servicios' %}
                            {% for catalogs in cant_services %}
                                {% if catalogs.id == catalogo.id and catalogo.type_catalog == 'Servicios' %}
                                    <h3 id="cantProduct-{{forloop.counter}}">{{catalogs.cantSer}}</h3>
                                {% endif %}
                            {% endfor %}
                            {% endif %}

                            <h4>Productos Disponibles</h4>
                            <p>{{catalogo.description}}</p>
                            <button id="btn-opc-{{catalogo.id}}" class="btn-opc">Opciones</button>
                        </div>
                    </div>
                    <div id="card-funciones-{{catalogo.id}}" class="card-funciones">
                        <div class="card-funciones-opc">
                            <div class="card-funciones-opc-cerrar">
                                <a class="cerrar-ventana" id="cerrar-ventana-{{catalogo.id}}"><i class="fa-regular fa-circle-xmark"></i></a>
                            </div>
                            <div id="content-btn">
                                <a href="{% url 'edicionCatalogo' catalogo.id %}"><i class="fa-solid fa-pen-to-square"></i>Editar</a>
                            </div>
                            <div id="content-btn">
                                <a id="eliminar-{{catalogo.id}}"><i class="fa-solid fa-trash"></i>Borrar</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% empty %}
                <h2>Aun no tienes catalogos</h2>
                {% endfor %}
            </div>
            <div class="paginacion">
                <span class="step-links">
                    {% if  catalogos.has_previous %}
                        <a href="?page=1">&laquo; Primero</a>
                        <a href="?page={{  catalogos.previous_page_number }}">Anterior</a>
                    {% endif %}
                    <span class="current">
                        Pagina {{  catalogos.number }} de {{  catalogos.paginator.num_pages }}.
                    </span>
                    {% if  catalogos.has_next %}
                        <a href="?page={{  catalogos.next_page_number }}">Siguiente</a>
                        <a href="?page={{  catalogos.paginator.num_pages }}">Ultima &raquo;</a>
                    {% endif %}
                </span>
            </div>
            <div class="modal">
                <div class="content-modal">
                    <h2 class="content-modal-titulo">¿Deseas eliminar tu catalogo?</h2>
                    <a id="si">Si</a>
                    <a id="no">No</a>
                </div>
            </div>
        </div>
        
    </div>
    
{% endblock content %}

{% block script %}
<script src="{% static '../static/js/jquery-3.6.4.js' %}"></script>
<script>
    $(document).ready(()=>{
        $('.card-funciones').hide()
    })
    {% for catalogo in catalogos %}
    $('#btn-opc-{{catalogo.id}}').click(function(){
        $('#card-catalogo-face-{{catalogo.id}}').hide('slow');
        $('#card-funciones-{{catalogo.id}}').css('opacity','100');
        $('#card-funciones-{{catalogo.id}}').show('slow');
        
    })
    {% endfor %}

    {% for catalogo in catalogos %}
    $('#cerrar-ventana-{{catalogo.id}}').click(function(){
        $('#card-funciones-{{catalogo.id}}').hide('slow')
        $('#card-funciones-{{catalogo.id}}').css('opacity','100');
        $('#card-catalogo-face-{{catalogo.id}}').show('slow')
    })
    {% endfor %}

    {% comment %} Modal {% endcomment %}
    {% for catalogo in catalogos %}
    $('#eliminar-{{catalogo.id}}').click(function(e){
        $('.modal').addClass("modal--show")
        $('#si').attr('href','{% url 'eliminarCatalogo' catalogo.id %}')
    })

    $('#no').click(function(){
        $('.modal').addClass("modal")
    })

    {% endfor %}
</script>

<script type="text/javascript">
    
</script>
{% endblock script %}

company/templates/company_templates/crud-catalogo/select-profile.html
{% extends 'company_templates/layouts/layout.html' %}
{% load static %}
{% block title %}
    Seleccionar Perfil
{% endblock title %}

{% block content %}
    <div class="content-catalogos">
        {% include 'company_templates/layouts/layout-dashboard.html' %} 
        <div class="content-catalogos-perfiles">
            <h1>Selecciona tus catalogos</h1>
            <h2>Tus perfiles:</h2>
            <div class="content-catalogos-perfiles-general">            
                {% for perfil in perfiles %}
                <div class="content-catalogos-perfiles-general-card">
                    <div class="content-catalogos-perfiles-general-card-box">
                        <a href="agregar-catalogo/{{perfil.id}}">
                            <div class="perfil-imagen">
                                <img src="{{perfil.photo_profile.url}}">
                            </div>
                            <div class="perfil-descripcion">
                                {{perfil.name}}
                            </div>
                        </a>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="paginacion">
                <span class="step-links">
                    {% if  page_perfiles.has_previous %}
                        <a href="?page=1">&laquo; Primero</a>
                        <a href="?page={{  page_perfiles.previous_page_number }}">Anterior</a>
                    {% endif %}
                    <span class="current">
                        Pagina {{  page_perfiles.number }} de {{  page_perfiles.paginator.num_pages }}.
                    </span>
                    {% if  page_perfiles.has_next %}
                        <a href="?page={{  page_perfiles.next_page_number }}">Siguiente</a>
                        <a href="?page={{  page_perfiles.paginator.num_pages }}">Ultima &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
    </div>
{% endblock content %}

company/templates/company_templates/crud-catalogo/update-catalog.html
{% extends 'company_templates/layouts/layout.html' %}
{% load static %}
{% block title %}
    Editar Catalogo
{% endblock title %}

{% block content %}

{% comment %} Mensaje de error {% endcomment %}
    {% for message in messages %}
    {% if message.tags == 'error' %}
        <p id="error">{{message}}</p>
    {% else %}
    <p id="success">{{message}}</p>
    {% endif %} 
    {% endfor %}  
{% comment %} Fin {% endcomment %} 

    <div class="content-catalogos">
        {% include 'company_templates/layouts/layout-dashboard.html' %} 
        <div class="content-catalogos-general">
            {% comment %} <div class="content-bussines-general-errors"> 
                <p>{{form.errors}}</p>  
            </div> {% endcomment %}
            <div class="content-form">
                <h1>Editar catalogo</h1>
                <h3>Actualmente estas editando el catalogo:  <span style="color:red"> {{catalogo.name}}</span></h3>
                {% include "company_templates/layouts/form.html" %}
            </div>
        </div> 
    </div> 
{% endblock content %}

{% block script %}
    <script src="{% static '../static/js/jquery-3.6.4.js' %}"></script>
    <script>
    $(document).ready(()=>{
        $('#id_name').val('{{catalogo.name}}')       
        $('#id_description').val('{{catalogo.description}}')
        $('#id_profile').val('{{catalogo.profile_id}}')
        $('#id_category').val('{{catalogo.category.id}}')
        $('#id_type_catalog').val('{{catalogo.category.type_categorie}}')
    })

     // Solo imagenes
     $('input[type=file]').attr('accept','image/.jpg, .png, .jpeg, .webp');

        //Editar recuadro de imagen para Editar
        $('#photo_portada').html('<input type="file" name="photo_product1" accept="image/.jpg, .png, .jpeg, .webp" id="id_photo_product1"><div id="msg-file-11" style="position:relative; bottom:70px; font-size:12px; text-align:center;"><p style="color:#7D05B4;">Puedes editar tu imagen aqui</p><p id="ruta">{{catalogo.photo_portada}}</p></div>')

     $('#photo_portada').on("change", function(){
        if($('id_photo_portada').value != ""){
            const archivo = this.value.replace('C:\\fakepath\\','')
            $('#msg-file-photo_portada').html('<div style="position:relative; bottom:43px; font-size:12px; text-align:center;"><input type="file" name="photo_product4" accept="image/.jpg, .png, .jpeg, .webp" id="id_photo_product1"><p>Se a cargado la nueva imagen</p><p style="display:relative; top:2px;" id="arc-14"></p></div>')  
            $('#arc-photo_portada').html(archivo)  
        } 
    })

    </script>
{% endblock script %}