otawind/urls.py
from django.contrib import admin
from django.urls import include, path
from company import views
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.conf.urls import handler404

urlpatterns = [
    path('generar_url/', views.generar_url, name="generar_url"),
    path('url_catalogo/', views.generar_url, name="url_catalogo"),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', views.home, name="home"),
    path('home/<str:name>', views.index, name="index"),
    path("registro", views.signUp, name="registro"),
    path("accounts/login/", views.logIn, name="ingreso"),
    path('logout/', views.logOut, name="logout"),
    path('creacion/', views.createAccount, name="creacion"),
    path('dashboard/<str:name>/',login_required(views.dashboard), name="dashboard"),
    path('bussines-profile/',login_required(views.bussines), name="bussines"),
    path('perfil/<str:name>/<int:id>',login_required(views.profile), name="perfil"),
    path('edicion-perfil/<int:id>',login_required(views.editionProfile), name="edicionPerfil"),
    path('seleccionar-perfil',login_required(views.selectCatalog), name="selectPerfil"),
    path('agregar-catalogo/<int:id>',login_required(views.addCatalog), name="addCatalogo"),
    path('ver-catalogo/<str:name>/<int:id>', login_required(views.viewCatalogUser), name="viewCatalogo"),
    path('edicion-catalogo/<int:id>', login_required(views.editCatalog), name="edicionCatalogo"),
    path('eliminar-catalogo/<int:id>', login_required(views.deleteCatalog), name="eliminarCatalogo"),
    path('productos/<str:name>/<int:id>', login_required(views.viewProduct), name="productos"),
    path('agregar-producto/<str:name>/<int:id>', login_required(views.addProduct), name="addProductos"),
    path('editar-producto/<str:name>/<int:id>', login_required(views.editProduct), name="edicionProducto"),
    path('eliminar-producto/<int:id>', login_required(views.deleteProduct), name="eliminarProducto"),
    path('servicios/<str:name>/<int:id>', login_required(views.viewService), name="servicios"),
    path('agregar-servicio/<str:name>/<int:id>', login_required(views.addService), name="addServicios"),
    path('editar-servicio/<str:name>/<int:id>', login_required(views.editService), name="edicionServicio"),
    path('perfil-usuario/<str:name>/<int:id>', login_required(views.view_profile), name="viewPerfil"),
    path('catalogo/<str:name_profile>/<str:name>/<int:id>', views.viewCatalog, name="verCatalogo"),
    path('acerca-de-otawind/', views.acercaDe, name="acercaDe"),
]



# cONFIGURACION PARA CARGAR IMAGENES
if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

company/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Color(models.Model):
    name = models.CharField(max_length=30)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="fecha creacion")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="fecha actualizacion")

class Account(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    photo_profile = models.ImageField(upload_to="perfil_bussines", verbose_name="perfil", null=True)
    birthday = models.DateTimeField(auto_now=False, auto_now_add=False, verbose_name="Cumpleaños")
    country = models.CharField(max_length=50, verbose_name='Pais')
    city = models.CharField(max_length=50, verbose_name='Ciudad')
    bio = models.TextField(max_length=50, null=True)
    email = models.EmailField(max_length=254, verbose_name='Correo')
    facebook = models.CharField(max_length=300, null=True)
    instagram = models.CharField(max_length=300, null=True)
    whatsapp = models.CharField(max_length=300, null=True)
    indicative = models.CharField(max_length=3, verbose_name="Indicativo")
    contact = models.CharField(null=True, max_length=30, verbose_name="Contacto")
    gender = models.CharField(
        verbose_name = 'Genero',
        null=True,
        max_length=6,
        choices=[('Hombre','Hombre'),('Mujer','Mujer'),('Otros','Otros')]
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="fecha creacion")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="fecha actualizacion")

    def __str__(self):
        return self.user.username
    

class Category(models.Model):
    name = models.CharField(max_length=200, verbose_name = "Nombre")
    type_categorie = models.CharField(max_length=15, verbose_name= "tipo_categoria")
    description = models.TextField(verbose_name="descripcion")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="fecha creacion")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="fecha actualizacion")

    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"
    
    def __str__(self):
        return self.name
    
class ProfileBussines(models.Model):
    name = models.CharField(max_length=100, verbose_name="nombre")
    user = models.ForeignKey(User, verbose_name="usuario" , on_delete=models.CASCADE)
    bio = models.TextField(max_length=50, null=True)
    category = models.ForeignKey(Category, verbose_name="categoria", on_delete=models.CASCADE, default=True)
    photo_portada = models.ImageField(upload_to="perfil_bussines", verbose_name="portada", null=True)
    photo_profile = models.ImageField(upload_to="perfil_bussines", verbose_name="perfil", null=True)
    description = models.TextField(max_length=500, verbose_name="descripcion")
    contact = models.CharField(max_length=50, verbose_name="contacto")
    email = models.EmailField(max_length=254, verbose_name="correo")
    facebook = models.CharField(max_length=300, null=True)
    instagram = models.CharField(max_length=300, null=True)
    whatsapp = models.CharField(max_length=300, null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="fecha creacion")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="fecha actualizacion")
    class Meta:
        verbose_name = "Perfil-Empresa"
        verbose_name_plural = "Perfiles-Empresas"

    
    def __str__(self):
        return self.name

class Catalogos(models.Model):
    name = models.CharField(max_length=40, verbose_name="nombre")
    user = models.ForeignKey(User, verbose_name="user", on_delete=models.CASCADE, null=True)
    profile = models.ForeignKey(ProfileBussines, verbose_name="perfil", on_delete=models.CASCADE, null=True)
    category = models.ForeignKey(Category, verbose_name="categoria", on_delete=models.CASCADE)
    type_catalog = models.CharField(
        max_length = 10,
        verbose_name = 'Tipo catalogo',
        choices = [('Servicios','Servicios'),('Productos','Productos')]
    )
    description = models.TextField(max_length=1000, null=True, verbose_name="descripcion")
    photo_portada = models.ImageField(upload_to="catalogo", verbose_name="portada", null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="fecha creacion")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="fecha actualizacion")
    class Meta:
        verbose_name = "Catalogo"
        verbose_name_plural = "Catalogos"
    
    def __str__(self):
        return self.name
    
class Products(models.Model):
    name_product = models.CharField(max_length=100, verbose_name="Nombre")
    user = models.ForeignKey(User, verbose_name="user", on_delete=models.CASCADE)
    catalog = models.ForeignKey(Catalogos, verbose_name="catalogo", on_delete=models.CASCADE, related_name='product')
    id_product = models.CharField(max_length=10, unique=True, verbose_name="id_producto")
    profile = models.ForeignKey(ProfileBussines, verbose_name="Perfil", on_delete=models.CASCADE, null=True)
    category = models.ForeignKey(Category, verbose_name="Categoria", on_delete=models.CASCADE, default="None")
    quantities = models.CharField(max_length=4, verbose_name="Cantidades", null=True)
    brand = models.CharField(max_length=30, verbose_name="Marca")
    status = models.CharField(max_length=20, verbose_name="estado", default='Activo')
    color = models.CharField(max_length=50, null=True)
    valoration = models.CharField(verbose_name="Valoracion", max_length=3, default='3.5')
    price = models.IntegerField(verbose_name="precio")
    price_promo = models.IntegerField(verbose_name='promocion', default="0")
    description = models.TextField(max_length=1000, verbose_name="descripcion", default="Descripcion del producto")
    photo_product1 = models.ImageField(upload_to="productos", verbose_name="foto_producto1")
    photo_product2 = models.ImageField(upload_to="productos", verbose_name="foto_producto2", null=True)
    photo_product3 = models.ImageField(upload_to="productos", verbose_name="foto_producto3", null=True)
    photo_product4 = models.ImageField(upload_to="productos", verbose_name="foto_producto4", null=True)
    class Meta:
        verbose_name = "Producto"
        verbose_name_plural = "Productos"
    
    def __str__(self):
        return self.name_product
    

class Services(models.Model):
    name_service = models.CharField(max_length=40, verbose_name="Nombre")
    user = models.ForeignKey(User, verbose_name="user", on_delete=models.CASCADE)
    catalog = models.ForeignKey(Catalogos, verbose_name="catalogo", on_delete=models.CASCADE, related_name='service')
    id_service = models.CharField(max_length=10, unique=True, verbose_name="id_servicio")
    profile = models.ForeignKey(ProfileBussines, verbose_name="Perfil", on_delete=models.CASCADE, null=True)
    category = models.ForeignKey(Category, verbose_name="Categoria", on_delete=models.CASCADE, default="None")
    valoration = models.CharField(verbose_name="Valoracion", max_length=3, default='3.5')
    status = models.CharField(max_length=20, verbose_name="estado", default='Activo')
    price = models.IntegerField(verbose_name="precio")
    price_promo = models.IntegerField(verbose_name='promocion', default="0")
    description = models.TextField(max_length=1000, verbose_name="descripcion", default="Descripcion del servicio")
    photo_service1 = models.ImageField(upload_to="servicios", verbose_name="foto_servicio1")
    photo_service2 = models.ImageField(upload_to="servicios", verbose_name="foto_servicio2", null=True)
    photo_service3 = models.ImageField(upload_to="servicios", verbose_name="foto_servicio3", null=True)
    photo_service4 = models.ImageField(upload_to="servicios", verbose_name="foto_servicio4", null=True)
    class Meta:
        verbose_name = "Servicio"
        verbose_name_plural = "Servicios"
    
    def __str__(self):
        return self.name_service

company/templates/company_templates/crud-productos/add-product.html
{% extends 'company_templates/layouts/layout.html' %}
{% load static %}
{% block title %}
    Agregar producto
{% endblock title %}

{% block content %}
    <div class="content-producto">
        {% include 'company_templates/layouts/layout-dashboard.html' %}
        <div class="content-producto-general">
            {% comment %} Mensaje flash {% endcomment %}
            {% for msg in messages %}
            {% if msg.tags == 'error' %}
            <div id="flash-error">
                <div id="content-error"><p>{{msg}}</p></div>
            </div>
            {% else %}
            <div id="flash-success">
                <div id="content-success"><p>{{msg}}</p></div>
            </div>
            {% endif %}
            {% endfor %}
            {% comment %} Fin mensaje flash {% endcomment %}
            <div class="content-form">
                <h1>Añade tus productos</h1>
                {% include "company_templates/layouts/form.html" %}
            </div>
            
        </div> 
    </div> 
{% endblock content %}

{% block script %}
<script src="{% static '../static/js/jquery-3.6.4.js' %}"></script>
<script>
    $(document).ready(()=>{
        $('#id_price').on('input', function () { 
            this.value = this.value.replace(/[^0-9]/,'');
        });

        $('#id_quantities').on('input', function () { 
            this.value = this.value.replace(/[^0-9]/,'');
        });


        setTimeout(function(){
            $('#flash-succes').fadeOut(1500);
            $('#flash-error').fadeOut(1500);
        }, 3000);

        
        //Agregando texto a los recuadros de input type="file"
        $('#msg-file-photo_product1').html('<div style="cursor:pointer; text-align:center;"><i style="color:#7D05B4;" class="fa-regular fa-upload"><span style="font-size:14px;">Seleccionar</span></i><span style="font-size:14px"> o arrastrar el archivo hasta aqui.</span><p style="font-size:12px; text-align:center;">Sube tu imagen en JPG, PNG, JPEG, WEBP hasta de 5 MB de peso.</p></div>')
        $('#msg-file-photo_product2').html('<div style="cursor:pointer; text-align:center;"><i style="color:#7D05B4;" class="fa-regular fa-upload"><span style="font-size:14px;">Seleccionar</span></i><span style="font-size:14px"> o arrastrar el archivo hasta aqui.</span><p style="font-size:12px; text-align:center;">Sube tu imagen en JPG, PNG, JPEG, WEBP hasta de 5 MB de peso.</p></div>')
        $('#msg-file-photo_product3').html('<div style="cursor:pointer; text-align:center;"><i style="color:#7D05B4;" class="fa-regular fa-upload"><span style="font-size:14px;">Seleccionar</span></i><span style="font-size:14px"> o arrastrar el archivo hasta aqui.</span><p style="font-size:12px; text-align:center;">Sube tu imagen en JPG, PNG, JPEG, WEBP hasta de 5 MB de peso.</p></div>')
        $('#msg-file-photo_product4').html('<div style="cursor:pointer; text-align:center;"><i style="color:#7D05B4;" class="fa-regular fa-upload"><span style="font-size:14px;">Seleccionar</span></i><span style="font-size:14px"> o arrastrar el archivo hasta aqui.</span><p style="font-size:12px; text-align:center;">Sube tu imagen en JPG, PNG, JPEG, WEBP hasta de 5 MB de peso.</p></div>')

            // Solo imagenes
            $('input[type=file]').attr('accept','image/.jpg, .png, .jpeg, .webp');
        

        // Validacion de INPUT file
        $('#id_photo_product1').on("change", function(){
            if($('id_photo_product1').value != null){
                console.log('vacio')
            }else{
                const archivo = this.value.replace('C:\\fakepath\\','')
                //const nameArc = archivo.replace('fakepath',' ')
                $('#msg-file-photo_product1').html('<div> <p style="font-size:12px; text-align:center;">Se a cargado su imagen con exito.</p></div>')
                $('#arc-photo_product1').html(archivo)  
            }  
        })

        $('#id_photo_product2').on("change", function(){
            if($('id_photo_product2').value != null){
                console.log('vacio')
            }else{
                const archivo = this.value.replace('C:\\fakepath\\','')
                //const nameArc = archivo.replace('fakepath',' ')
                $('#msg-file-photo_product2').html('<div> <p style="font-size:12px; text-align:center;">Se a cargado su imagen con exito.</p></div>')
                $('#arc-photo_product2').html(archivo)  
            }  
        })

        $('#id_photo_product3').on("change", function(){
            if($('id_photo_product3').value != null){
                console.log('vacio')
            }else{
                const archivo = this.value.replace('C:\\fakepath\\','')
                //const nameArc = archivo.replace('fakepath',' ')
                $('#msg-file-photo_product3').html('<div> <p style="font-size:12px; text-align:center;">Se a cargado su imagen con exito.</p></div>')
                $('#arc-photo_product3').html(archivo)  
            }  
        })

        $('#id_photo_product4').on("change", function(){
            if($('id_photo_product4').value != null){
                console.log('vacio')
            }else{
                const archivo = this.value.replace('C:\\fakepath\\','')
                //const nameArc = archivo.replace('fakepath',' ')
                $('#msg-file-photo_product4').html('<div> <p style="font-size:12px; text-align:center;">Se a cargado su imagen con exito.</p></div>')
                $('#arc-photo_product4').html(archivo)  
            }  
        })
        
    })
</script>
{% endblock script %}

company/templates/company_templates/crud-productos/edit-product.html
{% extends 'company_templates/layouts/layout.html' %}
{% load static %}
{% block title %}
    Editar producto
{% endblock title %}

{% block content %}
    <div class="content-producto">
        {% include 'company_templates/layouts/layout-dashboard.html' %}
        <div class="content-producto-general">
            <div class="content-form">
                <h1>Editar producto</h1>
                {% include "company_templates/layouts/form.html" %}
            </div>
        </div> 
    </div> 
{% endblock content %}

{% block script %}
<script src="{% static '../static/js/jquery-3.6.4.js' %}"></script>
<script>
    $(document).ready(()=>{
        $('#id_catalog').val('{{producto.catalog.id}}')
        $('#id_profile').val('{{producto.profile.id}}')
        $('#id_name_product').val('{{producto.name_product}}')
        $('#id_quantities').val('{{producto.quantities}}')
        $('#id_description').val('{{producto.description}}')
        $('#id_status').val('{{producto.status}}')
        $('#id_brand').val('{{producto.brand}}')
        $('#id_valoration').val('{{producto.valoration}}')
        $('#id_price').val('{{producto.price}}')
        $('#id_price_promo').val('{{producto.price_promo}}')
        $('#id_color').val('{{producto.color}}')
        setTimeout(function() {
            $("#flash-success").fadeOut(1500);
            $("#flash-error").fadeOut(1500);
        },3000);

    })

    $('#btn-cancelar').click(function(){
        $('.modal-form').removeClass("modal--show");
    });


    // Solo imagenes
    $('input[type=file]').attr('accept','image/.jpg, .png, .jpeg, .webp');

    //Editar recuadro de imagen para Editar
    $('#photo_product1').html('<input type="file" name="photo_product1" accept="image/.jpg, .png, .jpeg, .webp" id="id_photo_product1"><div id="msg-file-11" style="position:relative; bottom:70px; font-size:12px; text-align:center;"><p>Puedes editar tu imagen aqui</p><p>{{producto.photo_product1}}</p></div>')
    $('#photo_product2').html('<input type="file" name="photo_product2" accept="image/.jpg, .png, .jpeg, .webp" id="id_photo_product2"><div id="msg-file-12" style="position:relative; bottom:70px; font-size:12px; text-align:center;"><p>Puedes editar tu imagen aqui</p><p>{{producto.photo_product2}}</p></div>')
    $('#photo_product3').html('<input type="file" name="photo_product3" accept="image/.jpg, .png, .jpeg, .webp" id="id_photo_product3"><div id="msg-file-13" style="position:relative; bottom:70px; font-size:12px; text-align:center;"><p>Puedes editar tu imagen aqui</p><p>{{producto.photo_product3}}</p></div>')
    $('#photo_product4').html('<input type="file" name="photo_product4" accept="image/.jpg, .png, .jpeg, .webp" id="id_photo_product4"><div id="msg-file-14" style="position:relative; bottom:70px; font-size:12px; text-align:center;"><p>Puedes editar tu imagen aqui</p><p>{{producto.photo_product4}}</p></div>')

    // Validacion de INPUT file
    $('#id_photo_product1').on("change", function(){
        if($('id_photo_product1').value != ""){
            const archivo = this.value.replace('C:\\fakepath\\','')
            $('#msg-file-11').html('<div style="position:relative; bottom:43px; font-size:12px; text-align:center;"><input type="file" name="photo_product1" accept="image/.jpg, .png, .jpeg, .webp" id="id_photo_product1"><p>Se a cargado la nueva imagen</p><p style="display:relative; top:2px;" id="arc-11"></p></div>')  
            $('#arc-11').html(archivo)  
        } 
    })

    $('#id_photo_product2').on("change", function(){
        if($('id_photo_product2').value != ""){
            const archivo = this.value.replace('C:\\fakepath\\','')
            $('#msg-file-12').html('<div style="position:relative; bottom:43px; font-size:12px; text-align:center;"><input type="file" name="photo_product2" accept="image/.jpg, .png, .jpeg, .webp" id="id_photo_product2"><p>Se a cargado la nueva imagen</p><p style="display:relative; top:2px;" id="arc-12"></p></div>')  
            $('#arc-12').html(archivo)  
        } 
    })

    $('#id_photo_product3').on("change", function(){
        if($('id_photo_product3').value != ""){
            const archivo = this.value.replace('C:\\fakepath\\','')
            $('#msg-file-13').html('<div style="position:relative; bottom:43px; font-size:12px; text-align:center;"><input type="file" name="photo_product3" accept="image/.jpg, .png, .jpeg, .webp" id="id_photo_product3"><p>Se a cargado la nueva imagen</p><p style="display:relative; top:2px;" id="arc-13"></p></div>')  
            $('#arc-13').html(archivo)  
        } 
    })

    $('#id_photo_product4').on("change", function(){
        if($('id_photo_product4').value != ""){
            const archivo = this.value.replace('C:\\fakepath\\','')
            $('#msg-file-14').html('<div style="position:relative; bottom:43px; font-size:12px; text-align:center;"><input type="file" name="photo_product4" accept="image/.jpg, .png, .jpeg, .webp" id="id_photo_product4"><p>Se a cargado la nueva imagen</p><p style="display:relative; top:2px;" id="arc-14"></p></div>')  
            $('#arc-14').html(archivo)  
        } 
    })
</script>
{% endblock script %}

company/templates/company_templates/crud-productos/view-product.html
{% extends 'company_templates/layouts/layout.html' %}
{% load static %}
{% block title %}
    Productos
{% endblock title %}

{% block content %}
    <div class="content-producto">
        {% include 'company_templates/layouts/layout-dashboard.html' %}
        <div class="content-producto-general">
             {% comment %} Mensaje flash {% endcomment %}
            {% for msg in messages %}
            {% if msg.tags == 'error' %}
            <div id="flash-error">
                <div id="content-error"><p>{{msg}}</p></div>
            </div>
            {% else %}
            <div id="flash-success">
                <div id="content-success"><p>{{msg}}</p></div>
            </div>
            {% endif %}
            {% endfor %}
            {% comment %} Fin mensaje flash {% endcomment %}
            <h2 id="titulo-productos">Productos</h2>
            <div class="content-producto-general-navbar">
                <div class="btn-opc">
                    <div class="btn-opc-boton">
                        <a href="{% url "addProductos" name=request.user.username id=request.user.id %}">
                            <i class="fa-brands fa-product-hunt"></i>
                            <h4>Añadir producto</h4>
                        </a>
                    </div>
                </div>
                <div class="content-filters">
                    <h4>Filtros aplicados:</h4><a href="{% url "productos" name=request.user.username id=request.user.id %}" id="deleteFilter"><i class="fa-sharp fa-solid fa-filter-circle-xmark"></i></a>
                    <ul>
                    {% if query != None %}
                        <li><p> <span>Producto:</span> {{query}} </p></li>
                    {% else %}
                        <li><p> <span>Producto:</span> </p></li>
                    {% endif %}
                    {% if filter_category != None %}
                        <li><p> <span>Categoria:</span> {{filter_category}} </p></li>
                    {% else %}
                        <li><p> <span>Categoria:</span> </p></li>
                    {% endif %}
                    {% if filter_catalog != None %}
                        <li><p> <span>Catalogo:</span> {{filter_catalog}} </p></li>
                    {% else %}
                        <li><p> <span>Catalogo:</span> </p></li>
                    {% endif %}
                    </ul>
                </div>
            </div>
            <div class="content-producto-general-tabla">
                <form class="form-product">
                    <label>Producto:</label>
                    <input type="text" placeholder="Producto, codigo, descripcion" name="buscar" id="productName" class="productName" value="{{query}}">
                    <label>Categoria</label>
                    <select name="category">
                        {% if filter_category != None %}
                            <option value="{{filter_category}}">{{filter_category}}</option>
                            {% else %}
                            <option value=""></option>
                        {% endif %}
                        {% for category in category %}
                            <option value="{{category.name}}">{{category.name}}</option>
                        {% endfor %}
                    </select>
                    <label>Catalogo</label>
                    <select name="catalog">
                        {% if filter_category != None %}
                            <option value="{{filter_catalog}}">{{filter_catalog}}</option>
                            {% else %}
                            <option value=""></option>
                        {% endif %}
                        {% for catalogs in catalogs %}
                            <option value="{{catalogs.name}}">{{catalogs.name}}</option>
                        {% endfor %} 
                    </select>
                    <button id="buscar"><i class="fa-solid fa-magnifying-glass"></i></button>
                </form>
                <table class="tabla-productos">
                    <tr>
                        <th id="id">ID</th>
                        <th id="idProducto">ID Producto</th>
                        <th id="producto">Producto</th>
                        <th id="catalogo">Catalogo</th>
                        <th id="imagen">Imagen</th>
                        <th id="precio">Precio</th>
                        <th id="cantidad">Cantidad</th>
                        <th id="estado">Estado</th>
                        <th id="funciones">Funciones</th>
                    </tr>
                    {% for producto in productos %}
                    <tr class="tabla-productos-datos">
                        <td>{{producto.id}}</td>
                        <td>{{producto.id_product}}</td>
                        <td id="name_product">{{producto.name_product}}</td>
                        <td>{{producto.catalog.name}}</td>
                        <td id="foto-producto"><img src="{{producto.photo_product1.url}}"></td>
                        <td>{{producto.price}}</td>
                        <td>{{producto.quantities}}</td>
                        {% if producto.status == 'Activo' %}
                            <td style="color:#7F38B4">{{producto.status}}</td>
                        {% else %}
                        <td style="color:red">{{producto.status}}</td>
                        {% endif %}
                        
                        <td> <a><i class="fa-solid fa-eye"></i></a> | <a id="editar-{{producto.id}}" href="{% url "edicionProducto" name=request.user.username id=producto.id %}"><i class="fa-solid fa-wand-magic-sparkles"></i></a> | <a id="eliminar-{{producto.id}}"><i class="fa-solid fa-trash"></i></a> </td>
                    </tr>
                    {% empty %}
                    <h2 id="no-found">No se encontraron productos</h2>
                    {% endfor %}
                </table>
            </div>
        </div> 
        <div class="modal">
            <div class="content-modal">
                <h2 class="content-modal-titulo">¿Deseas eliminar tu catalogo?</h2>
                <a id="si">Si</a>
                <a href="">No</a>
            </div>
        </div>
    </div> 
{% endblock content %}

{% block script %}
<script src="{% static '../static/js/jquery-3.6.4.js' %}"></script>
<script>
    $(document).ready(()=>{
        setTimeout(function() {
            $("#success").fadeOut(1500);
        },3000);
    })

    {% comment %} Modal {% endcomment %}
    {% for producto in productos %}
    $('#eliminar-{{producto.id}}').click(function(e){
        $('.modal').addClass("modal--show")
        $('#si').attr('href','{% url 'eliminarProducto' producto.id %}')
    })
    {% endfor %}

    $('#btn-cancelar').click(function(){
        $('.modal-form').removeClass("modal--show");
    });
</script>
{% endblock script %}